name: Build Yattee

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: macos-14  # Required for Xcode and Apple toolchain

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app  # Ensures the latest Xcode is used

      - name: Build for iOS Simulator
        run: xcodebuild clean build -project Yattee.xcodeproj -scheme "Yattee (iOS)" -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Upload build artifacts (optional)
        if: success()  # Runs only if builds succeed
        uses: actions/upload-artifact@v4
        with:
          name: yattee-build-artifacts
          path: |
            build/  # Adjust path to where build outputs are stored
          retention-days: 5  # Artifacts available for download for 5 days
